# Pocket Pro — Leave table generator.
# Runs the classifier test suite first; on green, emits:
#   1. PocketProCore/Sources/PocketProCore/Generated/LeaveTable.swift  (1,023 pre-resolved entries)
#   2. docs/leave_audit.csv                                            (human QA audit table)
# Usage: powershell -File generate.ps1
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

Write-Host 'Running classifier test suite before generation...'
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'tests.ps1') | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host 'Classifier tests FAILED — refusing to generate. Run tests.ps1 for details.' -ForegroundColor Red
    exit 1
}
Write-Host 'Tests green. Generating...'

. (Join-Path $PSScriptRoot 'classifier.ps1')

$names = Get-NameMap

# ---- Build packed table ----
$packed = New-Object int[] 1024
$audit = New-Object System.Collections.Generic.List[string]
$audit.Add('pins,mask,primary,tags,name')
for ($mask = 1; $mask -le 1023; $mask++) {
    $standing = @(Get-Standing $mask)
    $tags = @(Get-Categories $standing)
    $p = 0
    foreach ($t in $tags) { $p = $p -bor (1 -shl (Get-CategoryBit $t)) }
    $packed[$mask] = $p
    $name = ''
    if ($names.ContainsKey($mask)) { $name = $names[$mask] }
    $audit.Add(('{0},{1},{2},{3},{4}' -f ($standing -join '-'), $mask, $tags[0], ($tags -join '+'), $name))
}

# ---- Emit Swift ----
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// AUTO-GENERATED by tools/classifier/generate.ps1 - DO NOT EDIT BY HAND.')
[void]$sb.AppendLine('// Pre-resolved leave classification lookup table (PRD 5.5.3).')
[void]$sb.AppendLine('// All 1,023 non-strike pin combinations classified at build time;')
[void]$sb.AppendLine('// the app performs no rule evaluation at runtime.')
[void]$sb.AppendLine('// Bit positions match LeaveCategory.rawValue. Mask: bit (pin-1) set = pin standing.')
[void]$sb.AppendLine('// Validated by tools/classifier/tests.ps1 (PRD 5.5.2 decision log + invariants).')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// swiftlint:disable all')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('public enum LeaveTable {')
[void]$sb.AppendLine('    /// packed[mask] = category bitset. Index 0 (strike / no pins standing) is 0.')
[void]$sb.AppendLine('    public static let packed: [UInt16] = [')
for ($row = 0; $row -lt 64; $row++) {
    $line = '        '
    for ($col = 0; $col -lt 16; $col++) {
        $idx = $row * 16 + $col
        $line += ('0x{0:X4}, ' -f $packed[$idx])
    }
    [void]$sb.AppendLine($line.TrimEnd())
}
[void]$sb.AppendLine('    ]')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    /// Display names for named leaves, keyed by standing-pin bitmask.')
[void]$sb.AppendLine('    public static let names: [Int: String] = [')
foreach ($key in ($names.Keys | Sort-Object)) {
    [void]$sb.AppendLine(('        {0}: "{1}",' -f $key, $names[$key]))
}
[void]$sb.AppendLine('    ]')
[void]$sb.AppendLine('}')

$swiftPath = Join-Path $repoRoot 'PocketProCore\Sources\PocketProCore\Generated\LeaveTable.swift'
[System.IO.File]::WriteAllText($swiftPath, $sb.ToString(), [System.Text.Encoding]::ASCII)
Write-Host "Wrote $swiftPath"

$csvPath = Join-Path $repoRoot 'docs\leave_audit.csv'
[System.IO.File]::WriteAllLines($csvPath, $audit.ToArray(), [System.Text.Encoding]::ASCII)
Write-Host "Wrote $csvPath ($($audit.Count - 1) rows)"

# ---- Sanity: spot-check packed values against direct classification ----
$spot = @(@(7,10), @(1,5), @(2,4,5,8), @(10))
foreach ($pins in $spot) {
    $m = Get-Mask $pins
    $expected = 0
    foreach ($t in @(Get-Categories @($pins))) { $expected = $expected -bor (1 -shl (Get-CategoryBit $t)) }
    if ($packed[$m] -ne $expected) {
        Write-Host "SPOT CHECK FAILED for $($pins -join '-')" -ForegroundColor Red
        exit 1
    }
}
Write-Host 'Generation complete, spot checks green.' -ForegroundColor Green
exit 0
